// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vzzqqjzcikflvlyoblss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6enFxanpjaWtmbHZseW9ibHNzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NzI4ODUsImV4cCI6MjA3MTU0ODg4NX0.-ZQiq1YFc9u_KyP6U4ali3wmlt1P2ipeVFG_pSPHa04";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});